---

- name: Copy Nagios Monitoring Role
  copy: src=roles/nagios-mon/ dest=/opt/openstack-ansible/playbooks/roles/nagios-mon/
  tags: 
    - nagios_mon_role
    - update_nagios_monitoring_files
    - nagios

- name: Copy nagios_mon.yml
  copy: src=nagios-mon-containers.yml dest=/opt/openstack-ansible/playbooks/nagios-mon-containers.yml
  tags: 
    - nagios_mon_yml
    - nagios
    
- name: Run Nagios-Mon Playbook
  shell: ansible-playbook nagios-mon-containers.yml -e "nagios_ipv4_ip={{nagios_ipv4_ip}}" chdir=/opt/openstack-ansible/playbooks/
  changed_when: false
  tags: 
    - run_nagios_mon_playbook
    - update_nagios_monitoring_files
    - nagios