---
  
  - name: restart
    become: true
    command: shutdown -r now "Ansible reboot triggered"
    async: 0
    poll: 0
    ignore_errors: true
    notify: wait for reboot

  - name: wait for reboot
    pause: seconds=60
